<?xml version="1.0" encoding="utf-8"?><Database Name="Test" Class="StudentDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CPI" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>